[package]
name = "rs-process-monitor"
version = "0.1.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
sysinfo = "0.37.2"
chrono = "0.4.42"
ratatui = "0.30.0"
crossterm = "0.29.0"
